spring:
  sql:
    init:
      mode: never
  datasource:
    username: ${PACKAGES_DB_USERNAME}
    password: ${PACKAGES_DB_PASSWORD}
    url: ${PACKAGES_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    user: ${PACKAGES_DB_USERNAME}
    password: ${PACKAGES_DB_PASSWORD}
    url: ${PACKAGES_DB_URL}
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true

bot:
  api-url: https://api.telegram.org/
  path: ${WEBHOOK}
  name: packages
  token: ${TOKEN}

dir:
  for:
    write: batches

